//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice05_MacaronsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Macaron
    {
        public int ID { get; set; }
        public string Flavor { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
