//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice05_MacaronData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAST7DAYS
    {
        public string PASTDATE { get; set; }
        public Nullable<int> QTYTOTAL { get; set; }
        public Nullable<decimal> NETTOTAL { get; set; }
        public Nullable<decimal> GROSSTOTAL { get; set; }
    }
}
