//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice05_MacaronData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderItem
    {
        public int orderID { get; set; }
        public int orderItemID { get; set; }
        public Nullable<decimal> orderItemUPrice { get; set; }
        public Nullable<int> orderItemQty { get; set; }
        public Nullable<decimal> orderItemPrice { get; set; }
        public Nullable<decimal> orderItemTax { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
